services:
  postgres:
    image: postgres:16
    container_name: auth-api-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  api:
    build: .
    container_name: auth-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/authdb?schema=public
      JWT_SECRET: ${JWT_SECRET:-dev_secret_key_change_in_production_123456789}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - postgres
    networks:
      - auth-network
    volumes:
      - ./src:/app/src
      - /app/node_modules

volumes:
  postgres_data:
    driver: local

networks:
  auth-network:
    driver: bridge
